---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(nflverse)
library(tidymodels)
library(tidyverse)
```

```{r}
pbp <- load_pbp()
player_stats <- load_player_stats()
player_stats_kicking <- load_player_stats(stat_type = "kicking")
roster <- load_rosters()
team_data <- load_teams()

# roster has the images and full names and number... what other data?
# other stats as well :)

#save(pbp, player_stats, file="mystuff.Rdata")
#load("mystuff.Rdata")
```

```{r}
# filter the roster for the data about the player
filtered_roster <- roster %>% filter(full_name == "Joe Burrow")

# filter the stats for the player data
j_burrow_raw <- player_stats %>% filter(grepl(filtered_roster$last_name, player_name)) %>% mutate_if(is.character, as.factor)
```

```{r}
# average the numeric columns
j_burrow_num <- j_burrow_raw %>% 
  summarise(across(where(is.numeric), mean)) %>% mutate_if(is.numeric, round, digits = 2)

# leave the factors alone and change table length
j_burrow_fact <- j_burrow_raw %>% slice_head(n = 1) %>% select(where(is.factor)) %>% select(!season_type)

# bind the tables
j_burrow <- bind_cols(j_burrow_fact, j_burrow_num, filtered_roster)
# not sure if below line is responsible...
j_burrow_num <- j_burrow_num %>% select_if(~ !any(is.na(.)))
exp_j_burrow <- bind_cols(j_burrow_fact, filtered_roster)
# nest doesn't like NA or 0 data apparently
exp_j_burrow <- exp_j_burrow %>% nest(player_data = j_burrow_num)
# use nest to make some changes to how the data is displayed


# now we have lots of data :)
# for the desired player!!
```

```{r}
j_burrow_json <- jsonlite::toJSON(j_burrow)
## let's goooooooo
# here is a json of the data
# right now I'm passing averages 
# later will adjust to pass arrays of the data within
# the JSON
```

```{r}
## Let's turn this into a function :)

get_player_data <- function(player_name_query) {
  filtered_player_roster <- roster %>% filter(full_name == player_name_query)
  player_stats_raw <- player_stats %>% filter(grepl(filtered_roster$last_name, player_name)) %>% mutate_if(is.character, as.factor)
  player_numeric_data <- j_burrow_raw %>% 
  summarise(across(where(is.numeric), mean))
  player_factor_data <- j_burrow_raw %>% slice_head(n = 1) %>% select(where(is.factor)) %>% select(!season_type)
  player_team_data <- team_data %>% filter(team_abbr == player_factor_data$recent_team)
  full_player_data <- bind_cols(filtered_player_roster, player_numeric_data, player_factor_data, player_team_data)
  player_json <- jsonlite::toJSON(full_player_data)
  return(player_json)
}

get_player_data("Joe Burrow")
```

```{r}
get_player_data <- function(player_name_query) {
  filtered_player_roster <- roster %>% filter(full_name == player_name_query)
  if(filtered_player_roster$position == 'K') {
    player_stats_raw <- player_stats_kicker %>% filter(grepl(filtered_player_roster$last_name, player_name)) %>% mutate_if(is.character, as.factor)
  } else {
    player_stats_raw <- player_stats %>% filter(grepl(filtered_player_roster$last_name, player_name)) %>% mutate_if(is.character, as.factor)
  }
  player_numeric_data <- player_stats_raw %>% 
  summarise(across(where(is.numeric), mean))
  player_factor_data <- player_stats_raw %>% slice_head(n = 1) %>% select(where(is.factor)) %>% select(!season_type)
  full_player_data <- bind_cols(filtered_player_roster, player_numeric_data, player_factor_data)
  player_json <- jsonlite::toJSON(full_player_data)
  return(player_json)
}
get_player_data("Harrison Butker")
```
```{r}
unique(roster$position)

team_data <- load_teams()
```

